language: node_js
node_js:
  - "12"

script:
    - echo '***** Build Started *****'
    - echo 'Installing dependencies' 
    - npm install
    - npm test
notifications:
    email: mlsettimo@gmail.com